### ISSUE TITLE
Error msg window auto resize affects editor: Confusing

### ISSUE THREAD

**Issue by bwagner** [jwdj/EasyABC#12]
The error message window below the abc source text automatically resizes to accommodate the error message, messing up the abc source text just above.

It would be desirable to keep the error message window at a constant height, so as not to affect the source code above.

(EasyABC Version 1.3.5 on OS X 10.14.6 Mojave)

**Comment by jwdj** [comment]
EasyABC Version 1.3.5 is quite old. The most recent version is 1.3.7.7. Errors are now reported in Internals -> Messages
