### ISSUE TITLE
GStreamer errors despite having libfluidsynth

### ISSUE THREAD

**Issue by PigeonOnTheGate** [jwdj/EasyABC#27]
Hi
Thank you very much for resolving my last issue. I've been having another problem with easyABC as well: The program gives me Gstreamer errors despite the fact that I have GStreamer and wxwidgets (along with its media class) installed. I have also added libfluidsynth to the same directory as easyABC and added a soundfont in the settings. Despite this, I continue to get the GStreamer errors. How do I make GStreamer or FluidSynth work? Do I have to install another package, or am I missing something in the settings?

Thank you very much.

**Comment by jwdj** [comment]
Please get the latest source and read the updated instructions in 
using_EasyABC_in_Linux.txt
Hope that helps.

**Comment by PigeonOnTheGate** [comment]
Thank you
