### ISSUE TITLE
No sound on Linux ... and how to fix it.

### ISSUE THREAD

**Issue by louis-barman** [jwdj/EasyABC#38]
I am running Ubuntu 20.04.2 LTS and there is no sound when using fluidsynth on a fresh install.

I fixed this by editing `fluidsynthplayer.py` line 16 which I changed from `self.fs.start()` to `self.fs.start('pulseaudio')`

This is obviously not the correct solution for other OS's but it worked for me as no default output driver was being set. I am not sure where the default output driver should be set.

By the way the prefered audio driver on Ubuntu should be `pulseaudio` rather than `alsa`  because if `alsa` is used it locks the sound output and then no other apps can use the sound output.

I hope that is useful to others who have the same problem.

**Comment by jwdj** [comment]
The default sound driver for FluidSynth is now pulseaudio if OS is Linux.
