### ISSUE TITLE
titletrim

### ISSUE THREAD

**Issue by PaulFackler** [jwdj/EasyABC#4]
%%titletrim 1 seems to be ignored if the last word is more than 5 characters. The ABC converter at http://www.mandolintab.net/abcconverter.php does not have this issue.

It would also be nice if this feature worked for groups of more than 1 word. For example
T:Montreal, Reel de
would be read as 
Reel de Montreal

**Comment by jwdj** [comment]
This cannot be fixed in EasyABC itself. You might want to send this request to the developer of abcm2ps
