### ISSUE TITLE
F (File) Info field is not output at the end of the tune 

### ISSUE THREAD

**Issue by ClintGoss** [jwdj/EasyABC#57]
I have an F: information field in my header of my tune and a directive in a .fmt file:
```
writefields COPQTWwNHRBDFSZ 1
```
... all of the other non-standard fields (NHRBDSZ) are shown at the end of the file, but not the F field.

**Comment by jwdj** [comment]
EasyABC only parses the output from abcm2ps. So if abcm2ps does not show the F field, EasyABC cannot add it for you.
You could ask the developer of abcm2ps to add this feature.
http://moinejf.free.fr/js/edit-1.xhtml
