### ISSUE TITLE
EasyABC .deb didn't declare it was dependent on wxgtk packages

### ISSUE THREAD

**Issue by robvdl** [jwdj/EasyABC#59]
When I installed the easyabc .deb at a friends house, it stated that all dependencies were satisfied, but upon launching the program it wanted some python3-gtk4wx packages which I had to install manually.

It should declare these packages as dependencies.

**Comment by robvdl** [comment]
fyi, I'm pretty good with Debian packaging if you need help

**Comment by jwdj** [comment]
Guido Gonzato from abcplus is probably the author of the easyabc.deb package. The migration from Python 2 to 3 has probably gone unnoticed and therefore the updating of the dependencies has not been done yet.
https://sourceforge.net/projects/abcplus/files/EasyABC/
It is not something that can be fixed here so I'm closing this issue.

**Comment by bomm** [comment]
@robvdl I would like to have a proper package for Ubuntu with correct dependencies.

I'm a software developer, but I don't have experience with creating Debian packages.
I found Debian packages here: https://sourceforge.net/projects/abcplus/files/EasyABC/. Is this what you tried?
The control file in the packages 1.3.7.8-1, 1.3.8-1 and 1.3.8.6-1 state in the Description field "(Converted from a rpm package by alien version 8.95.)". 
The insufficient dependencies might be a result of the conversion using `alien`. The source RPM contains this line in the spec file: `Requires:  python3, python-wxgtk4.0, python3-wxgtk-media4.0, python-pypm`

I would like to help in creating a Debian package.

Currently I'm using a quick and dirty solution on my systems.
I cloned the Git repository to `/usr/local/EasyABC` and created the attached file `/usr/share/applications/local-easyabc.desktop`  to get EasyABC into Ubuntu's application list using the file `logo256.png` as application icon. For a proper installation the location of the program would need to be changed. I also set the executable bit for `easy_abc.py`.

I noticed that the Debian package contains several useless files. It seems to be a copy of the Git sandbox. I thing we should clean up a bit.

[local-easyabc.desktop.txt](https://github.com/user-attachments/files/19847521/local-easyabc.desktop.txt)

**Comment by robvdl** [comment]
Fyi, not meaning to be grim, but the guy that asked for a deb actually passed away late last year. I don't have a need for a deb myself.

**Comment by bomm** [comment]
I created a first testing version of a Debian package. See 

- [my comment to #126](https://github.com/jwdj/EasyABC/issues/126#issuecomment-2907960271)
- the branch where I added the necessary files: https://github.com/bomm/EasyABC/tree/debian-package
- and my pre-release https://github.com/bomm/EasyABC/releases/tag/deb_1.3.8.7
