### ISSUE TITLE
Missing FluidSynth

### ISSUE THREAD

**Issue by marcstober** [jwdj/EasyABC#6]
Hi, I'm trying to run the source code, but I'm getting the error "ImportError: Couldn't find the FluidSynth library in the program directory." It looks like FluidSynth is a dependency that has been added since the last release of EasyABC on SourceForge. Can I get a certain DLL from somewhere? Or should I use an older version of the source code? (I'm not clear what FluidSynth does, was it suppose to fix something or add a new feature?) Thanks!

**Comment by jwdj** [comment]
[FluidSynth](http://www.fluidsynth.org/) is a real-time sample based software synthesizer. 
FluidSynth plays midi's files using so called sound fonts (with extension .sf2)

https://trisamples.com/free-soundfonts/
A popular allround soundfont is Fluid R3 GM

Thanks to Wim Vree who made modifications to FluidSynth and provided a working python binding we will have FluidSynth integration in EasyABC as of 1.3.7.8. No more need to use an external player.

You can enable the FluidSynth player by specify a valid soundfont in Settings -> Abc Settings -> File Settings

You can find a Windows DLL and a Ubuntu binary in the following location: 
https://wim.vree.org/svgParse/testplayer.html
It needs to be in the same folder as easy_abc.py / EasyABC.exe

So far it has been tested with Windows 10.

I have fixed the ImportError by the way.
