### ISSUE TITLE
feature request - play from selected note

### ISSUE THREAD

**Issue by tr4npt** [jwdj/EasyABC#69]
The Play position bar is difficult to use.  It's not very precise and the position follows the play position, which makes it tedious for repeatedly playing a specific part.  

I think it would be nice to have the Play button automatically start from the selected note.  If multiple notes are selected, then the Play button could play only the selection.

**Comment by topchyan** [comment]
I'm using version 1.3.8.7 on Linux (Debian) and cannot understand how to make use of this partial playback feature. I am highlighting either a line of notes or notes in the output score itself and push Play button, but the song plays from the start, not just the fragment that I am highlighting. Can you please explain how to use this feature properly? Thank you!
